export const ADD_CONTACT = 'CONTACTS/ADD CONTACT';
export const CHANGE_CONTACT = 'CONTACTS/CHANGE CONTACT';
export const DELETE_CONTACT = 'CONTACTS/DELETE COTNACT';
export const SET_CONTACTS = 'CONTACTS/SET CONTACTS';
export const SET_SEARCH_RESULT = 'SEARCH/SET SEARCH RESULT';
export const SEARCH = 'SEARCH/ SEARCH';
export const LOGIN = 'AUTH/LOGIN';
export const LOGOUT = 'AUTH/LOGOUT';
